# Generated by Django 3.0.2 on 2020-04-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='', upload_to='post_images'),
            preserve_default=False,
        ),
    ]
